POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Creando otra nota",
    "important": true
}

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Estudiar más sobre MongoDB"
}


###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "no-content-error": "Estudiar más sobre MongoDB",
    "important": true
}