POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Creando nota con usuario asignado",
    "important": true,
    "userId": "6877df6c9f6c7a56e95f4e16"
}

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Estudiar más sobre MongoDB",
    "userId": "6876655439f951485dd6a1d3"
}


###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "no-content-error": "Estudiar más sobre MongoDB",
    "important": true,
    "userId": "6876655439f951485dd6a1d3"
}